services:
  grafana:
    extends:
      file: .config/docker-compose-base.yaml
      service: grafana
    ports:
      - 3000:3000/tcp

  grafana-dev:
    image: ghcr.io/volkovlabs/app:latest@sha256:7255f71881b7aa94198da4760a3c74fbbc5f6d16b592ec55f69c40c4e479b7be
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_DASHBOARDS_DEFAULT_HOME_DASHBOARD_PATH=/etc/grafana/provisioning/dashboards/panels.json
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,marcusolsson-json-datasource,volkovlabs-variable-panel, volkovlabs-image-panel
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-form-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dev

  server:
    build:
      context: ./server-json
    ports:
      - 3001:3001/tcp
    profiles:
      - dev
      - main
      - dependency

  server-delay:
    build:
      context: ./server-delay
    ports:
      - 5002:5002/tcp
    profiles:
      - dev
      - main
      - dependency

  postgres:
    image: postgres@sha256:5773fe724c49c42a7a9ca70202e11e1dff21fb7235b335a73f39297d200b73a2
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432:5432
    volumes:
      - ./server-pg:/docker-entrypoint-initdb.d
    profiles:
      - dev
      - main
      - dependency
      - playwright

  server-pg:
    build:
      context: ./server-pg
    ports:
      - 3002:3001/tcp
    depends_on:
      - postgres
    environment:
      WAIT_HOSTS: postgres:5432
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_HOST: postgres
    profiles:
      - dev
      - main
      - dependency

  grafana-main:
    image: grafana/grafana:main@sha256:2259d4cd6885a94411fb15d677866ca7fcee1ab3449b14e37f644b606d01ad7c
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,marcusolsson-json-datasource,volkovlabs-variable-panel, volkovlabs-image-panel
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-form-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - main

  grafana-dep:
    image: grafana/grafana:11.0.0@sha256:0dc5a246ab16bb2c38a349fb588174e832b4c6c2db0981d0c3e6cd774ba66a54
    ports:
      - 3000:3000/tcp
    environment:
      - GF_DEFAULT_APP_MODE=development
      - GF_USERS_DEFAULT_THEME=light
      - GF_INSTALL_PLUGINS=marcusolsson-static-datasource,marcusolsson-json-datasource,volkovlabs-variable-panel, volkovlabs-image-panel
    volumes:
      - ./dist:/var/lib/grafana/plugins/volkovlabs-form-panel
      - ./provisioning:/etc/grafana/provisioning
    profiles:
      - dependency

  playwright:
    build:
      context: .
      dockerfile: test/Dockerfile
    environment:
      - GRAFANA_URL=http://grafana:3000
    volumes:
      - ./test:/app/test
      - ./playwright-report:/app/playwright-report
    depends_on:
      grafana:
        condition: service_healthy
    profiles:
      - e2e
